# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 18:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image', models.ImageField(default='fountain_images/default2.jpg', upload_to='fountain_images')),
                ('description', models.CharField(max_length=250)),
                ('floor', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('numberratings', models.IntegerField(default=0)),
                ('avgrating', models.FloatField(default=0)),
                ('popularity', models.IntegerField(default=0)),
                ('broken', models.BooleanField(default='false')),
                ('building', models.CharField(max_length=32)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2018, 3, 4, 18, 3, 3, 913758, tzinfo=utc), verbose_name='Date')),
                ('text', models.CharField(max_length=250)),
                ('fountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findafountain.Fountain')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findafountain.UserProfile'),
        ),
    ]
