# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findafountain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountain',
            name='avgrating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fountain',
            name='broken',
            field=models.BooleanField(default='False'),
        ),
    ]
