# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-04 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('findafountain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fountain',
            name='avgrating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 21, 57, 329078, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images'),
        ),
    ]
