# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('findafountain', '0002_auto_20180304_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 4, 21, 48, 18, 244792, tzinfo=utc), verbose_name='Date'),
        ),
    ]
