# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-05 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('findafountain', '0003_auto_20180304_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 5, 0, 58, 4, 280519, tzinfo=utc), verbose_name='Date'),
        ),
    ]
